title: Yolanda Tates # your name (or website title) here
logo: "/images/IMG_2198.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data-Driven Marketer 
  <br>
  Hello! I'm Yolanda. I'm a data-driven digital marketing professional with skills in SEO, email marketing, social media ads, and data analysis. 
  <a href="https://www.linkedin.com/in/yolandatates/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
